language: scala
scala:
  - 2.13.1
jdk:
  - openjdk8
env:
  global:
    - TIMEOUT_SEC=720
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
install:
  - git clone https://github.com/izgzhen/android-platforms
  - git clone https://github.com/izgzhen/msbase.scala
  - cd msbase.scala; sbt publishM2; cd -
  - git clone https://github.com/semantic-graph/semantic-graph.scala
  - cd semantic-graph.scala; sbt publishM2; cd -
script:
  - make init
  - make test
